Split translation and verification features.
spruceid/cacao-zcap-rs pull request #18
Opened 2022-04-22 17:43 UTC by cobward

Also re-export `cacaos`.

2022-04-25 22:57 UTC, clehner requested changes
CI failure: https://github.com/spruceid/cacao-zcap-rs/runs/6132810055?check_suite_focus=true#step:6:12

Commit id or branch for cacao-rs in the workflow file should be updated.

Can `cargo test` be made to pass? Examples (`examples/*.rs`) would need to be updated also for the new crate structure.

Looks like there are some residual uses of `cacaos::siwe`:
https://github.com/spruceid/cacao-zcap-rs/pull/18/files#r858084410
https://github.com/spruceid/cacao-zcap-rs/pull/18/files#r858082584

2022-04-26 14:19 UTC, clehner approved these changes

2022-05-09 12:05 UTC, chunningham approved these changes

2022-05-09 12:05 UTC, chunningham commented on src/translation/mod.rs
> +pub mod cacao2zcap;
catchy, but breaks snake_case module name convention

2022-05-09 12:57 UTC, cobward commented on src/translation/mod.rs
> +pub mod cacao2zcap;
good point, will fix.

2022-05-09 19:16 UTC, merged